new commit
MCServerWebManager/WebServerFrontend pull request #3
Opened 2023-08-23 19:51 UTC by swuY34

添加侧边栏: 跳转路由功能
修改项目结构
新增路由:
    - console
    - home
    - log
    - players
    - server
    - servers
    - world

2023-08-24 09:57 UTC, FHU-yezi requested changes
请在所有使用大括号的导入语句中，确保大括号与内容间有一个空格，如：

```typescript
import { SomeComponent } from "my-lib"
```

在组件中，对于字符串字面量，请移除多余的大括号。

对不会改变的 boolean 型组件参数，请使用二元语法，如 `open={true}` 可简写为 `open`。

请一并完成所有 comment 所述的更改。

2023-08-24 09:57 UTC, FHU-yezi commented on src/components/Sidebar/index.tsx
> +    ];
为避免在组件重新渲染时重复创建该数组，请将其移动到函数外变为全局变量。

2023-08-24 09:57 UTC, FHU-yezi commented on src/components/Sidebar/index.tsx
> +            open={ true }
请使用二元语法 `open`，该参数不会改变，不需要明确使用布尔值。

2023-08-24 09:57 UTC, FHU-yezi commented on src/pages/home/index.tsx
> +    return
请对占位空组件使用 `return null` 以避免类型错误。

2023-08-24 10:52 UTC, swuY34 commented
- 添加侧边栏折叠功能
- 优化对于 ts 的代码规范

2023-08-24 11:03 UTC, FHU-yezi approved these changes
LGTM

2023-08-26 16:39 UTC, zfzheng2000 commented
最好把 .idea 给去掉下

2023-08-26 16:53 UTC, zfzheng2000 approved these changes

2023-08-26 16:53 UTC, merged